### ISSUE TITLE
State of the project?

### ISSUE THREAD

**Issue by nodeful** [sentialx/node-window-manager#1]
Hey mate. 

Found your module because looking for a decent NodeJS Window manager for Linux.
What is the state of this module? I see you've only pushed it recently. 

NPM package does not exist, 404ing. Trying to `node-gyp rebuild` but says windows.h is missing.
I would be happy to contribute to this as I need to grab the whole list of available windows.

If you could point me in the right direction, I would appreciate that :)

**Comment by sentialx** [comment]
Currently node-window-manager is only supporting Windows, but in future there will be also support for linux and macOS. Try to install with npm install Sential/node-window-manager

**Comment by nodeful** [comment]
Oh right. I haven't worked with V8 API and node-gyp in general. But I will try to make some research and see if I can help in any way with Linux/macOS. Good work, keep it up.
