### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by alexweininger** [sentialx/node-window-manager#2]
Seems that Python 2 is a dependency... does not like Python 3. Caused by node-gyp.

![image](https://user-images.githubusercontent.com/12476526/53458747-20fc9500-39ec-11e9-9c92-a397365ce908.png)

I am trying to get Python 2 and fix the issue now.

Oh by the way, I am on Windows 10 with Python 3.7.2

**Comment by alexweininger** [comment]
Oh by the way, I am on Windows 10 with Python 3.7.2

**Comment by alexweininger** [comment]
Found some info here:
https://github.com/nodejs/node-gyp#on-windows

and here:
https://github.com/nodejs/node-gyp/issues/809#issuecomment-155019383

**Comment by sentialx** [comment]
`node-gyp` requires Python 2 installed, not 3. Also, try installing all needed dependencies using
```bash
$ npm install --global windows-build-tools
```

**Comment by alexweininger** [comment]
thanks!
