### ISSUE TITLE
[Catalina] Accessing many window methods crashes application

### ISSUE THREAD

**Issue by takempf** [sentialx/node-window-manager#27]
When attempting to use methods like `getBounds` and `setBounds` on window objects acquired with `windowManager.getWindows`—or from `new Window`—the application crashes. I've been able to use these methods in the past on the window object returned by `windowManager.getActiveWindow()`. Is this some kind of permission or security issue?

I have an [Electron Fiddle](https://electronjs.org/fiddle) here: https://gist.github.com/Fauntleroy/84fde89e6ede40becffa1fe53132ab7b

Steps to reproduce:
- Be in OSX Catalina (maybe just OSX?)
- Load that fiddle
- Use the interface to select an application
- Set a start point (column, row) and an end point (column, row)
- Press "up" to resize the window
- The application should crash with an error dump

**Comment by sentialx** [comment]
Does it work for you on `1.3.0`?

**Comment by takempf** [comment]
@sentialx I'm not completely sure, but it would seem that the fiddle I posted now crashes on `windowManager.getWindows();`

**Comment by takempf** [comment]
I'm sorry, but I feel like I was misunderstood: this module now crashes on `windowManager.getWindows()`, and I'm not even sure `getBounds` or `setBounds` work. Should I file a new issue for `getWindows()` causing a crash?

**Comment by sentialx** [comment]
@Fauntleroy Does the `example.js` file work for you?

**Comment by takempf** [comment]
It does not, it seems to crash on `const window = windowManager.getActiveWindow();`.

**Comment by sentialx** [comment]
@Fauntleroy Could you try adding `windowManager.requestAccessibility()` to the top? I forgot about it.

**Comment by takempf** [comment]
I added it back to my test script. It either does nothing, or access has already been granted. In any case, the crashes still persist when trying to use just about any window method.

**Comment by sentialx** [comment]
What `node-window-manager` version do you use?

**Comment by takempf** [comment]
Electron Fiddle always installs the latest version of the module, so 1.3.1:

<img width="282" alt="image" src="https://user-images.githubusercontent.com/507047/70752122-cc11dd00-1ce6-11ea-9cc9-c938691c5490.png">

**Comment by sentialx** [comment]
Okay, it seems it works for me because I don't have macOS Catalina. I'm curious what did they change so that it doesn't work...

**Comment by sentialx** [comment]
@Fauntleroy Fixed in [2.0.0](https://github.com/sentialx/node-window-manager/releases/tag/v2.0.0), although the `window.getTitle` method will crash on macOS Catalina, because it needs some kind of desktop capturer permission (#32).

**Comment by takempf** [comment]
@sentialx I can confirm that my test script is now working as expected! The loss of `window.getTitle` is regrettable, but my primary goal is working!
