### ISSUE TITLE
better multi monitor support

### ISSUE THREAD

**Issue by alexweininger** [sentialx/node-window-manager#3]
For managing windows with a multi-monitor workspace. It would be nice to provide functions for getting information about each monitor.

Maybe something from here:
https://docs.microsoft.com/en-us/windows/desktop/api/Winuser/nf-winuser-getmonitorinfoa
or
https://docs.microsoft.com/en-us/windows/desktop/gdi/multiple-monitor-system-metrics

**Comment by sentialx** [comment]
@alexweininger Released in 2.0.0
