### ISSUE TITLE
window.bringToTop() doesn't work

### ISSUE THREAD

**Issue by ghost** [sentialx/node-window-manager#36]
**Bug description**
window.bringToTop flashes the window in the task bar as if it was focused, but doesn't bring it forward

**To Reproduce**
![image](https://user-images.githubusercontent.com/57961248/73017711-43f71b00-3dee-11ea-9ca0-a7d4aea80081.png)

**Expected behavior**
Bring to top should bring a window to top

**Details:**
 - Operating System: Windows 10
 - `node-window-manager` version: 2.0.1
 - Last known working `node-window-manager` version: Never used this before today

**Additional context**
Working in electron, if that's relevant

**Comment by ghost** [comment]
Actually doing just about anything in electron breaks this.  Minimizing a window, then using restore, for example, freezes the application

**Comment by sentialx** [comment]
I also observed that bringing Electron BrowserWindows to top doesn't work.

**Comment by stefnotch** [comment]
[This answer on StackOverflow ](https://stackoverflow.com/questions/916259/win32-bring-a-window-to-top/34414846#34414846) does appear to work.

**Comment by arejaycola** [comment]
@stefnotch Do you have an example of how that would look with this library?

**Comment by stefnotch** [comment]
You'd have to modify [the native code of this library](https://github.com/sentialx/node-window-manager/blob/master/lib/windows.cc#L259-L268). Sadly I'm not well versed enough in cpp to do this and then submit a PR.
