### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by ptrwtts** [sentialx/node-window-manager#4]
Is MacOS support being actively worked on? One potential lead for how to do it is Phoenix:

https://github.com/kasper/phoenix

**Comment by brumm** [comment]
I've tried to post a bounty for this issue on bountysource, but their site seems broken... I'd love to see macOS support and would pledge $50 for this.

**Comment by sentialx** [comment]
@brumm @ptrwtts I've added partial support for macOS in branch `macos`

What is supported:
- [x] `windowManager.getActiveWindow`
- [x] `windowManager.getWindows`
- [x] `windowManager` event `windowActivated`
- [x] `window.getBounds`
- [x] `window.getTitle`
- [x] `window.handle`
- [x] `window.process`
  - [x] `window.process.id`
  - [x] `window.process.path`
  - [x] `window.process.name`
- [x] `window.setBounds`
- [x] `window.isWindow`
- [x] `window.minimize`
- [x] `window.restore`
- [x] `window.bringToTop`
- [ ] `window.setOwner`
- [ ] `window.getOwner`
- [ ] `window.getOpacity`
- [ ] `window.setOpacity`
- [ ] `window.maximize`
- [ ] `window.show`
- [ ] `window.hide`

**Comment by sentialx** [comment]
Added support for macOS in 0.9.0.

**Comment by brumm** [comment]
Oh heck! I'll give this a spin today :) Thanks a lot!

**Comment by brumm** [comment]
Hey dude! This works pretty well!

It'd be awesome if you could add a method to get the window list as well.

Can I ask what caused you to go the swift-binary route instead of doing this as a native module?

**Comment by sentialx** [comment]
@brumm In c++ there is no Cocoa and AppKit, therefore I can't do most of the things as a native module.

**Comment by sentialx** [comment]
I will need to rewrite it as a native module, because one call takes 50ms.

**Comment by sentialx** [comment]
It seems there's no way to do that :/

**Comment by brumm** [comment]
Hm. I've done at least the window listing stuff in a native module before, not sure whether that's different to what you'd want to be doing. For what it's worth, it's at least possible to import Appkit. Here's what I was doing then, this is pre-nan: https://gist.github.com/brumm/958fbc4f5418ce60f963c25e9c96aa55

**Comment by sentialx** [comment]
Thank you for your gist, I'll try to rewrite it to C++
