### ISSUE TITLE
ELECTRON: Doesn't work with packaged app with version > 1.3.1

### ISSUE THREAD

**Issue by KASOGIT** [sentialx/node-window-manager#50]
**Bug description**

The node-window-manager package does not work once packaged within an electron app using a version > 1.3.1

**To Reproduce**
Build an electron app with electron builder adding the build config:
```
  "asar": {
    "smartUnpack": true,
    "externalAllowed": true
  },
  "asarUnpack": "./node_modules/node-window-manager/build",
```

**Expected behavior**
Once packaged the node-window-manager features like resizing, bring to top, ... should work with version 2.2.0 like it does with version 1.3.1

**Details:**
 - Operating System: macos
 - `node-window-manager` version: 2.2.0
 - Last known working `node-window-manager` version: 1.3.1

What does changed between v1.3.1 and v.2.x.x node-window-manager build that prevent the package from working once bundled with electron-builder ?

Note: always works fine in development mode

**Comment by sentialx** [comment]
Probably it has something to do with prebuildify

**Comment by xland** [comment]
@KASOGIT 

Try to remove 'extract-file-icon' dependency from the `node_modules/node-window-manager` package.json and the code files
It is help for me.

Electron:9.0.4
node-window-manager:^2.2.3
vue-cli-plugin-electron-builder:~1.4.6
WIN:10

**Comment by sentialx** [comment]
@KASOGIT Does it work now? You should be able to install the package directly from github.

**Comment by andrew-oreshko** [comment]
@sentialx I'm getting the same issue as @KASOGIT, same OS and last package version
All good in dev, but once packaged - it doesn't work
Could you give any input here please?

**Comment by andrew-oreshko** [comment]
@sentialx to make .bringToTop() work .requestAccessibility() function needs to be called
Would it be good to add it to the doc?
