### ISSUE TITLE
"Is not a valid Win32 application" error

### ISSUE THREAD

**Issue by fttx** [sentialx/node-window-manager#53]
**Bug description**
I use a Windows 10 x64 machine to build my electron app, but when I try to launch it from an ia32 machine, I get this:

![image](https://user-images.githubusercontent.com/5663423/93765416-24caba80-fc15-11ea-8443-9108ce335390.png)

Other native dependencies work properly.

**Details:**
 - Operating System: Windows 10
 - `node-window-manager` version: 2.2.3

Can you advise a fix?

**Comment by fttx** [comment]
I found that ia32 modules are not generated with the current setup. Adding --ia32 to prebuildify parameters generates this additional folder:

<img width="835" alt="Screen Shot 2020-09-21 at 14 39 00" src="https://user-images.githubusercontent.com/5663423/93767850-ca335d80-fc18-11ea-902a-bf7dc8f5f677.png">

**Comment by sentialx** [comment]
Do you rebuild the module with electron headers? e.g electron-builder install-app-deps

**Comment by fttx** [comment]
Yes 
<img width="1069" alt="Screen Shot 2020-09-22 at 07 19 12" src="https://user-images.githubusercontent.com/5663423/93846305-ef20e280-fca3-11ea-8543-d8d9a429f9b4.png">

**Comment by sentialx** [comment]
I think I will just remove prebuildify, because it causes a lot of problems.

**Comment by sentialx** [comment]
@fttx Does it work now? I released it under 2.2.4.

**Comment by fttx** [comment]
Yes, now the app starts, and everything works as expected. Thank you 😃
