### ISSUE TITLE
setBounds does not work on chrome windows

### ISSUE THREAD

**Issue by swaipdev** [sentialx/node-window-manager#56]
The bug happens when you try to setBounds of a MAXIMIZED Chrome window. 
The setBounds operation does not work, meaning you cannot resize the window, position it where you want, etc.
If you try setBounds on another window (ex., Powerpoint window) it works even if the window's maximized.
The bug CANNOT be reproduced if the Chrome window is not maximized.

**To Reproduce**
chrome_win is a pointer to a MAXIMIZED Chrome window 

chrome_win.setBounds({x: 365, y: 0, width: 600, height: 720})

**Expected behavior**
The windows should be resized accordingly to parameters. 

**Details:**
 - Operating System: Windows 10
 - `node-window-manager` version: 2.2.4
 - Last known working `node-window-manager` version: N/A

**Comment by lonestarx1** [comment]
Hi @swaipdev ,
Try doing chrome_win.restore() before performing chrome_win.setBounds()
This seems to solve the issue :)
